### ISSUE TITLE
Build of new image failed

### ISSUE THREAD

**Issue by beunick** [andrey0001/strongswan#2]
Hi, 
I tried to build a new image and I am having this issue:

**Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
The command '/bin/sh -c /usr/bin/yum -y update &&	/usr/bin/yum -y install epel-release &&	/usr/bin/yum -y install strongswan strongswan-libipsec iptables' returned a non-zero code: 1**

**Comment by andrey0001** [comment]
There is new alpine-based image. Please check alpine branch.
Since with centos happened something magic - I avoid to use centos.

CentOS images also fixed, you can build it now. It's happened because RH stop support CentOS and url-s of yum repo is changed.
